// Infrastructure Layer - Data Transfer Object (DTO)
// This represents the raw API response structure from wflexp.json

export interface WeatherApiResponse {
  stnname: string
  stnmod: number
  ver: number
  mac: string
  apmac: string
  ip: string
  ssid: string
  rssi: number
  wifimod: number
  lastboot: number
  uptime: number
  wflver: string
  loctime: number
  utctime: number
  tzone: number
  units: number
  conlati: number
  conlongi: number
  wfllati: number
  wfllongi: number
  tempout: string
  humout: string
  tempin: string
  humin: string
  windspd: string
  winddir: string
  windavg2: string
  windavg10: string
  gust: string
  gustdir: string
  bar: string
  bartr: string
  dew: string
  cdew: string
  chill: string
  heat: string
  thsw: string
  uv: string
  solar: string
  rainr: string
  storm: string
  rain15: string
  rain1h: string
  raind: string
  rain24: string
  rainmon: string
  rainyear: string
  etday: string
  etmon: string
  etyear: string
  xt: string[]
  xlt: string[]
  xst: string[]
  xh: string[]
  xsm: string[]
  xlw: string[]
  bat: string
  trbat: string
  foreico: string
  forrule: string
  sunrt: string
  sunst: string
  hlbar: string[]
  hlwind: string[]
  hltempin: string[]
  hlhumin: string[]
  hltempout: string[]
  hlhumout: string[]
  hldew: string[]
  hlchil: string[]
  hlheat: string[]
  hlthsw: string[]
  hlsolar: string[]
  hluv: string[]
  hlrainr: string[]
  hlxt0: string[]
  hlxt1: string[]
  hlxt2: string[]
  hlxt3: string[]
  hlxlt0: string[]
  hlxlt1: string[]
  hlxlt2: string[]
  hlxlt3: string[]
  hlxst0: string[]
  hlxst1: string[]
  hlxst2: string[]
  hlxst3: string[]
  hlxh0: string[]
  hlxh1: string[]
  hlxh2: string[]
  hlxh3: string[]
}
